fix: 元数据部分数据不准确
hanxu317317/city_pickers pull request #154
Opened 2023-02-09 09:10 UTC by limingnie

1.香港城区的数据展示不出来，key没映射上；
2.参考链接：https://www.mca.gov.cn/article/sj/xzqh/2020/2020/202003301019.html，发现了少许数据不准确（未全部校对）；

2023-02-09 09:12 UTC, hanxu317317 commented
ok. 收到. 这份数据有点老了.  我看一下合并后. 怎么再写一个脚本 更新一下.

2023-02-09 09:18 UTC, ipcjs requested changes

2023-02-09 09:18 UTC, ipcjs commented on lib/meta/province.dart
> +    "659005": {"name": "北屯市", "alpha": "w"},
没更新检索用的`alpha`

2023-02-09 09:18 UTC, ipcjs commented on lib/meta/province.dart
> +    "6590010": {"name": "胡杨河市", "alpha": "t"}
这个值长度不对

2023-02-09 09:42 UTC, ipcjs approved these changes

2023-02-10 07:29 UTC, hanxu317317 commented
LGTM

2023-02-10 07:32 UTC, merged

2023-02-10 07:57 UTC, hanxu317317 commented
city_pickers: ^1.2.1 已经发布